import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] used by the application.
///
/// Replace the placeholder values with the configuration generated by the
/// FlutterFire CLI or from your Firebase project settings. The same file can
/// be safely committed to source control because it does not contain secrets
/// beyond the public keys provided by Firebase.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: 'AIzaSyAPi19WCO5hsd-AKq491SSckHirxrTSuiI',
        appId: '1:401251291991:web:e35bc038aa7622baab6412',
        messagingSenderId: '401251291991',
        projectId: 'monitoring-sheet-b72bd',
        authDomain: 'monitoring-sheet-b72bd.firebaseapp.com',
        storageBucket: 'monitoring-sheet-b72bd.firebasestorage.app',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: 'AIzaSyAPi19WCO5hsd-AKq491SSckHirxrTSuiI',
          appId: '1:401251291991:android:5c5b5b5b5b5b5b5b',
          messagingSenderId: '401251291991',
          projectId: 'monitoring-sheet-b72bd',
          storageBucket: 'monitoring-sheet-b72bd.firebasestorage.app',
        );
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return const FirebaseOptions(
          apiKey: 'AIzaSyAPi19WCO5hsd-AKq491SSckHirxrTSuiI',
          appId: '1:401251291991:ios:5c5b5b5b5b5b5b5b',
          messagingSenderId: '401251291991',
          projectId: 'monitoring-sheet-b72bd',
          storageBucket: 'monitoring-sheet-b72bd.firebasestorage.app',
          iosBundleId: 'com.example.app',
        );
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        return const FirebaseOptions(
          apiKey: 'YOUR_DESKTOP_API_KEY',
          appId: 'YOUR_DESKTOP_APP_ID',
          messagingSenderId: 'YOUR_DESKTOP_MESSAGING_SENDER_ID',
          projectId: 'YOUR_PROJECT_ID',
          storageBucket: 'YOUR_STORAGE_BUCKET',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not configured for this platform.',
    );
  }
}
